version: '2'

services:
  mongo-_MONGO_DB_NAME_:
    image: mongo
    restart: always
    container_name: _MONGO_DB_NAME_
    environment:
      MONGO_INITDB_ROOT_USERNAME: _MONGO_DB_USER_
      MONGO_INITDB_ROOT_PASSWORD: _MONGO_DB_PASSWORD_
    ports:
      - _MONGO_DB_PORT_:27017

  mysql-_MYSQL_DB_NAME_:  
    image: mariadb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: _MYSQL_DB_NAME_
    environment:
      MYSQL_ROOT_PASSWORD: _MYSQL_DB_PASSWORD_
    ports:
      - _MYSQL_DB_PORT_:3306

  rabbitmq-_RABBIT_MQ_NAME_:
    image: 'rabbitmq:3.6-management-alpine'
    container_name: _RABBIT_MQ_NAME_
    restart: always
    ports:
      - _RABBIT_MQ_D_PORT_:5672
      - _RABBIT_MQ_M_PORT_:15672

  influxdb-_INFLUX_DB_NAME_:
    image: 'influxdb:1.7.10-alpine'
    container_name: _INFLUX_DB_NAME_
    restart: always
    ports:
      - _INFLUX_DB_PORT_:8086